/* eslint-disable react/no-unescaped-entities */
import Container from "@/components/shared/Container/Container";
import DashboardNavbar from "@/components/shared/Navbar/DashboardNavbar";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const RulesPage = () => {
  return (
    <div>
      <DashboardNavbar />
      <Container className="my-10">
        <Accordion
          type="single"
          collapsible
          className="w-full"
          defaultValue="item-1"
        >
          <AccordionItem value="item-1">
            <AccordionTrigger>
              <h3 className=" uppercase">Billing</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>How do I fund my account?</p>
              <p>
                ✺Now you can use cryptocurrency for automatic replenish the
                balance. ✺ Minimal deposit amount of cryptocurrency is 100$
                include gateway comission. Send exact amount on deposit page by
                specified address using calculator, otherwise there may be
                problems with processing the payment. Payment automatically
                credited to your account when we receive first confirmation of
                transaction from network. Amount for payment is shown taking
                into account the gateway commission. Address generated by system
                for deposit can only be used once. Each new replenishment must
                be restarted!
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-2">
            <AccordionTrigger>
              <h3 className=" uppercase">our teams</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>What rules do you have?</p>
              <p>
                ✺ By using our service you automatically agree with rules our
                service. ✺ Our service sells goods in one exemplar. ✺ Our
                service does not return funds from users balance. ✺ Our service
                checks the goods for valid before selling. ✺ Our service
                guarantees a quality goods, but we are not responsible for your
                skills.{" "}
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-3">
            <AccordionTrigger>
              <h3 className=" uppercase">replacement</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>What about replace?</p>
              <p>
                ✺ No problem. If you purchased a defective or invalid goods, you
                are entitled to a free replacement.
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-4">
            <AccordionTrigger>
              <h3 className=" uppercase">multiple access</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>What about multiple access?</p>
              <p>✺ No, we don't allow several users to use one account.</p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-5">
            <AccordionTrigger>
              <h3 className=" uppercase">locked issue</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>Why my profile is locked?</p>
              <p>✺ You attempted to hack or scam the service.</p>
            </AccordionContent>
          </AccordionItem>

        

          <AccordionItem value="item-7">
            <AccordionTrigger>
              <h3 className=" uppercase">updates</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>When the updates?</p>
              <p>✺ We strive to update records on a weekly basis.</p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-7">
            <AccordionTrigger>
              <h3 className=" uppercase">Bug</h3>
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-4 text-balance">
              <p>Encounter Bug?</p>
              <p>
                ✺If you encounter a bug, please report it through our support
                chart or Telegram. We appreciate your feedback and will work to
                resolve the issue promptly.
              </p>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </Container>
    </div>
  );
};

export default RulesPage;
